import * as assert from 'assert';
import * as http from 'http';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';

import { WebSocketServer, WebSocket } from 'ws';

import { WorkshopClient } from '../api/client';
import { ensureKeypair, ensureSshAccess } from '../remote/ssh';

// ---------------------------------------------------------------------------
// ensureKeypair
// ---------------------------------------------------------------------------

suite('ensureKeypair', () => {
  let tmpDir: string;

  setup(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workshop-ssh-'));
  });

  teardown(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  test('generates a private key file and an authorized_keys line', () => {
    const kp = ensureKeypair(tmpDir);

    assert.ok(fs.existsSync(kp.privateKeyPath));
    // Private key is in OpenSSH native format (generated by ssh-keygen).
    const priv = fs.readFileSync(kp.privateKeyPath, 'utf8');
    assert.ok(priv.startsWith('-----BEGIN OPENSSH PRIVATE KEY-----'), 'private key is OpenSSH format');

    // Public key line must be in authorized_keys format.
    assert.ok(kp.publicKeyLine.startsWith('ssh-ed25519 '), 'public key starts with ssh-ed25519');
    assert.ok(kp.publicKeyLine.includes('workshop-vscode'), 'public key includes comment');
  });

  test('is idempotent: second call returns the same key', () => {
    const first = ensureKeypair(tmpDir);
    const second = ensureKeypair(tmpDir);

    assert.strictEqual(first.publicKeyLine, second.publicKeyLine);
    assert.strictEqual(first.privateKeyPath, second.privateKeyPath);
  });

  test('private key file has mode 0600', () => {
    const { privateKeyPath } = ensureKeypair(tmpDir);
    const mode = fs.statSync(privateKeyPath).mode & 0o777;
    assert.strictEqual(mode, 0o600);
  });
});

// ---------------------------------------------------------------------------
// ensureSshAccess — integration via fake daemon
// ---------------------------------------------------------------------------

suite('ensureSshAccess over a fake workshopd socket', () => {
  let server: http.Server;
  let wss: WebSocketServer;
  let socketPath: string;
  let tmpDir: string;
  let capturedCommand: unknown;
  let capturedStdin: string;

  setup(async () => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'workshop-ssh-'));
    socketPath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'workshopd-')), 'workshop.socket');
    capturedCommand = undefined;
    capturedStdin = '';

    server = http.createServer((req, res) => {
      const sync = (result: unknown) => {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ type: 'sync', 'status-code': 200, result }));
      };

      if (req.method === 'POST' && req.url?.endsWith('/exec')) {
        const chunks: Buffer[] = [];
        req.on('data', (c: Buffer) => chunks.push(c));
        req.on('end', () => {
          capturedCommand = JSON.parse(Buffer.concat(chunks).toString('utf8'));
          res.writeHead(202, { 'Content-Type': 'application/json' });
          res.end(
            JSON.stringify({
              type: 'async',
              'status-code': 202,
              change: '1',
              result: { 'task-id': 'T1' },
            }),
          );
        });
        return;
      }

      if (req.method === 'GET' && req.url === '/v1/changes/1/wait') {
        sync({
          id: '1',
          kind: 'exec',
          status: 'Done',
          ready: true,
          tasks: [{ id: '1', kind: 'exec', status: 'Done', data: { 'exit-code': 0 } }],
        });
        return;
      }

      res.writeHead(404).end();
    });

    wss = new WebSocketServer({ server });
    wss.on('connection', (socket: WebSocket, req: http.IncomingMessage) => {
      if (req.url?.endsWith('/stdio')) {
        const stdinChunks: Buffer[] = [];
        socket.on('message', (data: Buffer, isBinary: boolean) => {
          if (isBinary) {stdinChunks.push(data);}
          else {capturedStdin = Buffer.concat(stdinChunks).toString('utf8');}
        });
      } else if (req.url?.endsWith('/stdout') || req.url?.endsWith('/stderr')) {
        socket.send(''); // empty = end-of-stream barrier
      }
      // control: stay silent
    });

    await new Promise<void>((resolve) => server.listen(socketPath, resolve));
  });

  teardown(async () => {
    wss.close();
    await new Promise<void>((resolve) => server.close(() => resolve()));
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  test('sends the public key as stdin to the exec endpoint', async () => {
    const client = new WorkshopClient({ socketPath });
    const { publicKeyLine } = ensureKeypair(tmpDir);

    await ensureSshAccess(client, 'p', 'web', tmpDir);

    assert.strictEqual(capturedStdin, `${publicKeyLine}\n`);
  });

  test('exec payload uses bash and the key-plant script', async () => {
    const client = new WorkshopClient({ socketPath });
    await ensureSshAccess(client, 'p', 'web', tmpDir);

    const body = capturedCommand as { command: string[] };
    assert.deepStrictEqual(body.command[0], 'bash');
    assert.deepStrictEqual(body.command[1], '-c');
    assert.ok(
      typeof body.command[2] === 'string' &&
        body.command[2].includes('authorized_keys'),
      'script references authorized_keys',
    );
  });
});
